version: '3'
services:
  dev-db:
    image: mariadb
    ports:
      - 3310:3306
    environment:
      - MARIADB_USER=web
      - MARIADB_PASSWORD=superrahasia
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=nest
    volumes:
      - ./_volumes/dev-db:/var/lib/mysql
    networks:
      - nest
  test-db:
    image: mariadb
    ports:
      - 3311:3306
    environment:
      - MARIADB_USER=web
      - MARIADB_PASSWORD=superrahasia
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=nest
    volumes:
      - ./_volumes/test-db:/var/lib/mysql
    networks:
      - nest
networks:
  nest:
