@host=http://localhost:5000
@coffeeId=1
@authHeader=expected_key

###
GET {{host}}/coffees HTTP/1.1

###
GET {{host}}/coffees/{{coffeeId}} HTTP/1.1
Authorization: {{authHeader}}

###
POST {{host}}/coffees HTTP/1.1
Authorization: {{authHeader}}
Content-Type: application/json

{
    "name": "Coffee #3"
}

###
POST {{host}}/coffees HTTP/1.1
Authorization: {{authHeader}}
Content-Type: application/json

{
    "name": "Coffee #4",
    "brand": "Nest",
    "flavors": ["caramel", "vanilla"]
}

###
PATCH {{host}}/coffees/{{coffeeId}} HTTP/1.1
Content-Type: application/json

{
    "flavors": ["macha"]
}

###
DELETE {{host}}/coffees/{{coffeeId}} HTTP/1.1